<?php

namespace AppBundle\Repository;

/**
 * AdFavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdFavRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkFav($user,$id)
    {
        $q=$this->getEntityManager()->createQuery("SELECT p from AppBundle:AdFav p  where p.idAd=:id AND p.user=:user")
            ->setParameter('id',$id)
            ->setParameter('user',$user);
        return $query=$q->getResult();

    }
}
