provider_homepage:
    path:     /
    defaults: { _controller: ProviderBundle:Default:index }

provider_addAd:
    path:     /addAd
    defaults: { _controller: ProviderBundle:Ads:addAd }

provider_showAd:
    path:     /showMyAds
    defaults: { _controller: ProviderBundle:Ads:showMyAds }

provider_delete:
    path:     /deleteAd{ad_id}
    defaults: { _controller: ProviderBundle:Ads:deleteAd }

provider_update:
    path:     /updateAd{ad_id}
    defaults: { _controller: ProviderBundle:Ads:updateAd }
